-- =========================================================
-- MediCore Schema — Oracle Database
-- Clean Re-runnable Setup: Drop existing tables safely
-- =========================================================
BEGIN
    FOR t IN (
        SELECT table_name FROM user_tables 
        WHERE table_name IN (
            'NOTIFICATION', 'DOCTOR_SCHEDULE', 'USER_SESSION', 'AUDIT_LOG',
            'PAYMENT', 'BILL_ITEM', 'BILL', 'LAB_TEST', 'ADMISSION',
            'BED', 'ROOM', 'PRESCRIPTION_ITEM', 'PRESCRIPTION', 'MEDICINE',
            'TREATMENT', 'APPOINTMENT', 'PATIENT', 'DOCTOR', 'STAFF', 'DEPARTMENT'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE "' || t.table_name || '" CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/

CREATE TABLE department (
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    department_name VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (department_id),
    CONSTRAINT uq_department_name UNIQUE (department_name)
);

CREATE TABLE staff (
    staff_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR2(150) NOT NULL,
    email VARCHAR2(150) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_staff PRIMARY KEY (staff_id),
    CONSTRAINT uq_staff_email UNIQUE (email),
    CONSTRAINT chk_staff_role
        CHECK (role IN (
            'ADMIN',
            'DOCTOR',
            'RECEPTIONIST',
            'PHARMACIST',
            'ACCOUNTANT'
        ))
);

CREATE TABLE doctor (
    doctor_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    staff_id NUMBER NOT NULL,
    department_id NUMBER NOT NULL,
    specialization VARCHAR2(150),
    CONSTRAINT pk_doctor PRIMARY KEY (doctor_id),
    CONSTRAINT uq_doctor_staff UNIQUE (staff_id),
    CONSTRAINT fk_doctor_staff
        FOREIGN KEY (staff_id)
        REFERENCES staff(staff_id),
    CONSTRAINT fk_doctor_department
        FOREIGN KEY (department_id)
        REFERENCES department(department_id)
);

CREATE TABLE patient (
    patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR2(150) NOT NULL,
    dob DATE NOT NULL,
    gender VARCHAR2(10),
    phone VARCHAR2(20) NOT NULL,
    blood_group VARCHAR2(5),
    balance_due NUMBER(10,2) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_patient PRIMARY KEY (patient_id),
    CONSTRAINT chk_patient_gender
        CHECK (gender IN ('MALE', 'FEMALE', 'OTHER')),
    CONSTRAINT chk_patient_balance
        CHECK (balance_due >= 0)
);

CREATE TABLE appointment (
    appointment_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_id NUMBER NOT NULL,
    doctor_id NUMBER NOT NULL,
    appointment_date DATE NOT NULL,
    appointment_time VARCHAR2(10) NOT NULL,
    reason VARCHAR2(500),
    status VARCHAR2(20) DEFAULT 'SCHEDULED' NOT NULL,
    CONSTRAINT pk_appointment PRIMARY KEY (appointment_id),
    CONSTRAINT fk_appointment_patient
        FOREIGN KEY (patient_id)
        REFERENCES patient(patient_id),
    CONSTRAINT fk_appointment_doctor
        FOREIGN KEY (doctor_id)
        REFERENCES doctor(doctor_id),
    CONSTRAINT chk_appointment_status
        CHECK (status IN ('SCHEDULED', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT uq_doctor_appointment
        UNIQUE (doctor_id, appointment_date, appointment_time)
);

CREATE TABLE treatment (
    treatment_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_id NUMBER NOT NULL,
    doctor_id NUMBER NOT NULL,
    appointment_id NUMBER,
    diagnosis VARCHAR2(500) NOT NULL,
    treatment_notes VARCHAR2(1000),
    treatment_date DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_treatment PRIMARY KEY (treatment_id),
    CONSTRAINT fk_treatment_patient
        FOREIGN KEY (patient_id)
        REFERENCES patient(patient_id),
    CONSTRAINT fk_treatment_doctor
        FOREIGN KEY (doctor_id)
        REFERENCES doctor(doctor_id),
    CONSTRAINT fk_treatment_appointment
        FOREIGN KEY (appointment_id)
        REFERENCES appointment(appointment_id),
    CONSTRAINT uq_treatment_appointment
        UNIQUE (appointment_id)
);

CREATE TABLE medicine (
    medicine_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    medicine_name VARCHAR2(200) NOT NULL,
    unit_price NUMBER(10,2) NOT NULL,
    stock_quantity NUMBER DEFAULT 0 NOT NULL,
    reorder_level NUMBER DEFAULT 20 NOT NULL,
    CONSTRAINT pk_medicine PRIMARY KEY (medicine_id),
    CONSTRAINT chk_medicine_price CHECK (unit_price >= 0),
    CONSTRAINT chk_medicine_stock CHECK (stock_quantity >= 0),
    CONSTRAINT chk_medicine_reorder CHECK (reorder_level >= 0)
);

CREATE TABLE prescription (
    prescription_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    treatment_id NUMBER NOT NULL,
    prescribed_date DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_prescription PRIMARY KEY (prescription_id),
    CONSTRAINT fk_prescription_treatment
        FOREIGN KEY (treatment_id)
        REFERENCES treatment(treatment_id)
);

CREATE TABLE prescription_item (
    prescription_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    prescription_id NUMBER NOT NULL,
    medicine_id NUMBER NOT NULL,
    dosage VARCHAR2(100) NOT NULL,
    frequency_per_day NUMBER NOT NULL,
    duration_days NUMBER NOT NULL,
    CONSTRAINT pk_prescription_item PRIMARY KEY (prescription_item_id),
    CONSTRAINT fk_prescription_item_prescription
        FOREIGN KEY (prescription_id)
        REFERENCES prescription(prescription_id),
    CONSTRAINT fk_prescription_item_medicine
        FOREIGN KEY (medicine_id)
        REFERENCES medicine(medicine_id),
    CONSTRAINT chk_frequency CHECK (frequency_per_day > 0),
    CONSTRAINT chk_duration CHECK (duration_days > 0)
);

CREATE TABLE room (
    room_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    room_number VARCHAR2(20) NOT NULL,
    ward_type VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_room PRIMARY KEY (room_id),
    CONSTRAINT uq_room_number UNIQUE (room_number)
);

CREATE TABLE bed (
    room_id NUMBER NOT NULL,
    bed_number NUMBER NOT NULL,
    is_occupied NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_bed PRIMARY KEY (room_id, bed_number),
    CONSTRAINT fk_bed_room
        FOREIGN KEY (room_id)
        REFERENCES room(room_id),
    CONSTRAINT chk_bed_occupied
        CHECK (is_occupied IN (0, 1))
);

CREATE TABLE admission (
    admission_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_id NUMBER NOT NULL,
    room_id NUMBER NOT NULL,
    bed_number NUMBER NOT NULL,
    admission_date DATE DEFAULT SYSDATE NOT NULL,
    discharge_date DATE,
    CONSTRAINT pk_admission PRIMARY KEY (admission_id),
    CONSTRAINT fk_admission_patient
        FOREIGN KEY (patient_id)
        REFERENCES patient(patient_id),
    CONSTRAINT fk_admission_bed
        FOREIGN KEY (room_id, bed_number)
        REFERENCES bed(room_id, bed_number),
    CONSTRAINT chk_admission_dates
        CHECK (discharge_date IS NULL OR discharge_date >= admission_date)
);

CREATE TABLE lab_test (
    lab_test_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_id NUMBER NOT NULL,
    doctor_id NUMBER NOT NULL,
    test_type VARCHAR2(150) NOT NULL,
    requested_date DATE DEFAULT SYSDATE NOT NULL,
    result VARCHAR2(1000),
    result_date DATE,
    status VARCHAR2(20) DEFAULT 'REQUESTED' NOT NULL,
    CONSTRAINT pk_lab_test PRIMARY KEY (lab_test_id),
    CONSTRAINT fk_lab_test_patient
        FOREIGN KEY (patient_id)
        REFERENCES patient(patient_id),
    CONSTRAINT fk_lab_test_doctor
        FOREIGN KEY (doctor_id)
        REFERENCES doctor(doctor_id),
    CONSTRAINT chk_lab_test_status
        CHECK (status IN ('REQUESTED', 'IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT chk_lab_test_result_date
        CHECK (result_date IS NULL OR result_date >= requested_date)
);

CREATE TABLE bill (
    bill_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_id NUMBER NOT NULL,
    bill_date DATE DEFAULT SYSDATE NOT NULL,
    total_amount NUMBER(10,2) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_bill PRIMARY KEY (bill_id),
    CONSTRAINT fk_bill_patient
        FOREIGN KEY (patient_id)
        REFERENCES patient(patient_id),
    CONSTRAINT chk_bill_total
        CHECK (total_amount >= 0)
);

CREATE TABLE bill_item (
    bill_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    bill_id NUMBER NOT NULL,
    item_type VARCHAR2(30) NOT NULL,
    description VARCHAR2(500),
    amount NUMBER(10,2) NOT NULL,
    CONSTRAINT pk_bill_item PRIMARY KEY (bill_item_id),
    CONSTRAINT fk_bill_item_bill
        FOREIGN KEY (bill_id)
        REFERENCES bill(bill_id),
    CONSTRAINT chk_bill_item_type
        CHECK (item_type IN (
            'CONSULTATION',
            'TREATMENT',
            'MEDICINE',
            'LAB_TEST'
        )),
    CONSTRAINT chk_bill_item_amount
        CHECK (amount >= 0)
);

CREATE TABLE payment (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    bill_id NUMBER NOT NULL,
    payment_date DATE DEFAULT SYSDATE NOT NULL,
    amount_paid NUMBER(10,2) NOT NULL,
    payment_mode VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_payment PRIMARY KEY (payment_id),
    CONSTRAINT fk_payment_bill
        FOREIGN KEY (bill_id)
        REFERENCES bill(bill_id),
    CONSTRAINT chk_payment_amount
        CHECK (amount_paid >= 0),
    CONSTRAINT chk_payment_mode
        CHECK (payment_mode IN (
            'CASH',
            'CARD',
            'UPI',
            'INSURANCE'
        ))
);

CREATE TABLE audit_log (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    table_name VARCHAR2(100) NOT NULL,
    record_id NUMBER NOT NULL,
    operation VARCHAR2(10) NOT NULL,
    old_data CLOB,
    changed_by VARCHAR2(150),
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_audit_log PRIMARY KEY (audit_id),
    CONSTRAINT chk_audit_operation
        CHECK (operation IN ('UPDATE', 'DELETE'))
);

CREATE TABLE user_session (
    session_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    staff_id NUMBER NOT NULL,
    login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    logout_time TIMESTAMP,
    CONSTRAINT pk_user_session PRIMARY KEY (session_id),
    CONSTRAINT fk_user_session_staff
        FOREIGN KEY (staff_id)
        REFERENCES staff(staff_id)
);

CREATE TABLE doctor_schedule (
    schedule_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    doctor_id NUMBER NOT NULL,
    day_of_week VARCHAR2(10) NOT NULL,
    start_time VARCHAR2(10) NOT NULL,
    end_time VARCHAR2(10) NOT NULL,
    CONSTRAINT pk_doctor_schedule PRIMARY KEY (schedule_id),
    CONSTRAINT fk_doctor_schedule_doctor
        FOREIGN KEY (doctor_id)
        REFERENCES doctor(doctor_id),
    CONSTRAINT chk_schedule_day
        CHECK (day_of_week IN (
            'MONDAY',
            'TUESDAY',
            'WEDNESDAY',
            'THURSDAY',
            'FRIDAY',
            'SATURDAY',
            'SUNDAY'
        )),
    CONSTRAINT chk_schedule_times
        CHECK (start_time < end_time)
);

CREATE TABLE notification (
    notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_id NUMBER,
    staff_id NUMBER,
    message VARCHAR2(1000) NOT NULL,
    notification_type VARCHAR2(50),
    is_read NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_notification PRIMARY KEY (notification_id),
    CONSTRAINT fk_notification_patient
        FOREIGN KEY (patient_id)
        REFERENCES patient(patient_id),
    CONSTRAINT fk_notification_staff
        FOREIGN KEY (staff_id)
        REFERENCES staff(staff_id),
    CONSTRAINT chk_notification_read
        CHECK (is_read IN (0, 1)),
    CONSTRAINT chk_notification_recipient
        CHECK (patient_id IS NOT NULL OR staff_id IS NOT NULL)
);